# Site settings
title: Paulo Serôdio
description: 'ISER,
                University of Essex'
url: 'https://pauloserodio.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Paulo M Serôdio'
  email: pamato@essex.ac.uk
  twitter_username: p_serodio
  facebook_username: paulo.serodio
  github_username:  pamato
  linkedin_username:  paulomserodio

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'default'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
#include: ["_pages"]
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
